SUBSYSTEM_DEF(ru_names)
    name = "RU Names"
    flags = SS_NO_FIRE

/datum/controller/subsystem/ru_names/Initialize()
	GLOB.cargorilla_names = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_cargorilla.txt")
	GLOB.carp_names = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_carp.txt")
	GLOB.clown_names = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_clown.txt")
	GLOB.commando_names = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_death_commando.txt")
	GLOB.ethereal_names = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_ethereal.txt")
	GLOB.first_names_female = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_first_female.txt")
	GLOB.first_names_male = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_first_male.txt")
	GLOB.first_names = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_first.txt")
	GLOB.golem_names = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_golem.txt")
	GLOB.hive_names = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_hive_names.txt")
	GLOB.last_names = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_last.txt")
	GLOB.lizard_names_female = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_lizard_female.txt")
	GLOB.lizard_names_male = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_lizard_male.txt")
	GLOB.martial_prefix = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_martial_prefix.txt")
	GLOB.megacarp_first_names = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_megacarp1.txt")
	GLOB.megacarp_last_names = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_megacarp2.txt")
	GLOB.mime_names = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_mime.txt")
	GLOB.moth_first = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_moth_first.txt")
	GLOB.moth_last = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_moth_last.txt")
	GLOB.nightmare_names = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_nightmare.txt")
	GLOB.ninja_names = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_ninjaname.txt")
	GLOB.ninja_titles = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_ninjatitle.txt")
	GLOB.operative_aliases = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_operative_alias.txt")
	GLOB.plasmaman_names = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_plasmaman.txt")
	GLOB.religion_names = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_religion.txt")
	GLOB.syndicate_monkey_names = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_syndicate_monkey.txt")
	GLOB.voidwalker_names = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_voidwalker.txt")
	GLOB.wizard_first = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_wizardfirst.txt")
	GLOB.wizard_second = world.file2list("modular_meta/ru_translate/ru_names/strings/ru_wizardsecond.txt")

	return SS_INIT_SUCCESS
